### ISSUE TITLE
Работа без sphinx

### ISSUE THREAD

**Issue by MrFallen** [bad-day/BotInc#1]
Добрый день, а можно ли сделать работу этого скрипта без sphinx? Что нужно сделать? В PHP мало чего понимаю.

**Comment by vtr0n** [comment]
Здравствуйте.
Да, можно. Нужно в MySQL в таблице answers поставить полнотекстовый индекс на поле output.
Также поменять в файле SphinxSearch.php методы search и get_unfounded. (Отправлять запросы не к sphinx, а к MySQL).
Могу на отдельной ветке внести изменения.

**Comment by MrFallen** [comment]
Буду очень благодарен если сделаете)

**Comment by vtr0n** [comment]
Внес изменения в другой ветке. Пожалуйста, проверьте, потому что не было php под рукой.
